# python train.py -config yamls/CIFAR100_test_linear_norm.yaml
T: 4
tau: 2
b: 128
epochs: 300
T_max: 300
lr: 0.1
weight_decay: 0.0005
dynamic_threshold: True
WS: False
BN: True
BN_type: "linear"
data_dir: "/root/autodl-tmp/cifar100"
dataset: "cifar100"
out_dir: "logs/cifar100"
