T: 4
tau: 2
b: 128
epochs: 300
T_max: 300
model: "online_spiking_resnet19"
model_type: "spiking"
lr: 0.1
weight_decay: 0.0002
dynamic_threshold: False
WS: False
BN: True
BN_type: "old"
data_dir: "/root/autodl-tmp/cifar100"
dataset: "cifar100"
out_dir: "logs/cifar100"
