T: 4
tau: 2
b: 128
epochs: 300
T_max: 300
model: "online_spiking_resnet19"
model_type: "spiking"
lr: 0.1
# loss_lambda: 0.05
# cannot trained with higher weight_decay
weight_decay: 0.00002
dynamic_threshold: False
WS: False
BN: True
BN_type: "new"
data_dir: "/root/autodl-tmp/cifar10"
dataset: "cifar10"
out_dir: "logs/cifar10"