T: 6 
tau: 2
b: 128
epochs: 100
T_max: 100
lr: 0.1
weight_decay: 0.0005
WS: False
BN: True
tau_online_level: 1
weight_online_level: 1
data_dir: "../../datasets/cifar10/"
dataset: "cifar10"
out_dir: "logs/cifar10"