T: 20
tau: 2
b: 128
lr: 0.02
epochs: 300
T_max: 300
weight_decay: 0.0005
loss_lambda: 0.001
T_train: 14
dynamic_threshold: True
WS: False
BN: True
BN_type: "new"
light_classifier: False
data_dir: "/root/autodl-tmp/dvs128_gesture"
dataset: "dvsgesture"
out_dir: "logs/DVSGesture"