T: 20
tau: 2
b: 16
lr: 0.001
epochs: 300
T_max: 300
weight_decay: 0.0005
loss_lambda: 0.001
drop_rate: 0.0
T_train: 14
WS: "True"
tau_online_level: 1
weight_online_level: 1
data_dir: "../../datasets/dvs128_gesture/"
dataset: "dvsgesture"
resume: "logs/DVSGesture/online_spiking_vgg11_ws__T_20_T_train_14_SGD_lr_0.001_tau_lvl_1_w_lvl_1_CosALR_300/checkpoint_max.pth"