T: 4
tau: 2
b: 128
epochs: 100
T_max: 100
model: "online_spiking_resnet34"
lr: 0.1
weight_decay: 0.00005
WS: False
BN: True
tau_online_level: 5
weight_online_level: 4
data_dir: "/home/data/public/ImageNet/"
dataset: "imagenet"
out_dir: "logs/imagenet"