T: 4
tau: 2
b: 256
epochs: 100
T_max: 100
model: "online_spiking_resnet34"
lr: 0.05
weight_decay: 0.00002
WS: False
BN: True
BN_type: "old"
tau_online_level: 1
weight_online_level: 1
data_dir: "/home/data/public/ImageNet/"
dataset: "imagenet"
out_dir: "logs/imagenet"