T: 4
tau: 2
b: 256
epochs: 100
T_max: 100
model: "online_spiking_resnet34"
model_type: "SEW"
lr: 0.1
weight_decay: 0.00002
dynamic_threshold: False
WS: False
BN: True
BN_type: "new"
data_dir: "/home/data/public/ImageNet/"
dataset: "imagenet"
out_dir: "logs/imagenet"
