T: 4
tau: 2
b: 256
epochs: 100
T_max: 100
model: "online_spiking_resnet34"
model_type: "SEW"
lr: 0.1
weight_decay: 0.00002
dynamic_threshold: True
WS: False
BN: True
BN_type: "old"
data_dir: "/root/autodl-tmp/imagenet/"
dataset: "imagenet"
out_dir: "logs/imagenet"
